import react from '@vitejs/plugin-react'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [react()],
  // Resolves the `@/*` alias straight from tsconfig.json — no plugin needed.
  resolve: { tsconfigPaths: true },
  test: {
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    restoreMocks: true,
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'html'],
      reportsDirectory: 'coverage',
      // Coverage gates apply to the logic layers only. Presentational sections are
      // verified by component tests without a hard numeric gate — see
      // .agents/06-testing.md ("Co mierzymy pokryciem").
      include: ['src/lib/**/*.ts', 'src/hooks/**/*.ts'],
      exclude: [
        'src/**/*.{test,spec}.{ts,tsx}',
        // Generated by scripts/prepare-images.mjs — data, not logic.
        'src/lib/images/blur.ts',
        // A dynamic import of a browser-only animation library. The rule that matters
        // here (never import GSAP statically) is enforced by lint, not by coverage, and
        // loading the real package in jsdom would test the library, not our code.
        'src/lib/motion/gsap.ts',
      ],
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 85,
        statements: 90,
      },
    },
  },
})
