/**
 * GENERATED by scripts/prepare-images.mjs — do not edit by hand.
 *
 * A 16px-wide preview per photograph, inlined as base64 and used as next/image's
 * `placeholder="blur"`. Static string paths (as opposed to static imports) do not get a
 * blur placeholder automatically, so it is precomputed here.
 *
 * Empty until the first run of `pnpm images:prepare`.
 */
const BLUR_DATA: Record<string, string> = {}

/**
 * Spread onto a next/image: `<Image {...blurProps(src)} ... />`.
 * Returns nothing for an unknown path, so a missing preview degrades to no placeholder
 * rather than to a build error.
 */
export function blurProps(src: string): { placeholder: 'blur'; blurDataURL: string } | object {
  const blurDataURL = BLUR_DATA[src]
  return blurDataURL ? { placeholder: 'blur', blurDataURL } : {}
}
